python/99-project/django-web/ExpPH/ExpPH/urls.py
# -*- coding: utf-8 -*-

from django.conf.urls import include, url, patterns
from django.conf.urls.static import static
from ExpPH.settings import STATIC_ROOT, STATIC_URL, MEDIA_ROOT, MEDIA_URL
from django.contrib import admin
from ExpPH.views import homePage, videoPage


# 动态加载 settings.py的 INSTALLED_APPS
# 以获得权限在 admin 后台进行编辑操作
admin.autodiscover() 

urlpatterns = [
               
    # 跳转到主页的 URL
    url(r'^$', 'ExpPH.views.homePage', name='index'),
    url(r'(?i)^index/$', homePage, name='index'),
    url(r'(?i)^expph/$', homePage, name='index'),
    url(r'(?i)^lyy289065406/$', homePage, name='index'),
    url(r'(?i)^homePage/$', homePage, name='index'),
    url(r'(?i)^home/$', homePage, name='index'),
    
    # 跳转到后台管理站点
    url(r'^expAdmin/', include(admin.site.urls)),
    
    # 跳转到相册站点（album有第3方包，SAE不支持，要注释）
    url(r'^album/', include('album.urls')),
    
    # 跳转到博客站点
    url(r'^blog/', include('blog.urls')),
    
    # 跳转到cms站点（cms有第3方包，SAE不支持，要注释）
    url(r'^cms/', include('cms.urls')),
    
    
    # 跳转到视频页面
    url(r'(?i)^video/$', videoPage, name='video'),
]

# 当settings的DEBUG=False时，Django不会自动加载静态资源，此时需要手动指定静态资源路由，
# 为了让页面可以访问 static 和 media 静态资源的路由规则
# show_indexes 属性表示可以通过浏览器直接访问该目录的资源，即完全公开了
urlpatterns += patterns('',
    url(r'^media/(?P<path>.*)$', 'django.views.static.serve', {'document_root': MEDIA_ROOT, 'show_indexes': True }, name='media'),
    url(r'^static/(?P<path>.*)$', 'django.views.static.serve', {'document_root': STATIC_ROOT }, name='static'),
)
urlpatterns += static(MEDIA_URL , document_root = MEDIA_ROOT)
urlpatterns += static(STATIC_URL, document_root = STATIC_ROOT)

python/99-project/django-web/ExpPH/album/urls.py
# -*- coding: utf-8 -*-

from django.conf.urls import url, patterns
from album.models import Item, Photo
from django.views.generic import TemplateView, DetailView, ListView

urlpatterns = patterns('',
    url(r'^$', 
        ListView.as_view(
            queryset = Item.objects.all(),
            context_object_name = 'item_list',
            template_name = 'AlbumIndex.html',
        ),
        name = 'AlbumIndex'
    ),
                   
    url(r'^items/$', 
        ListView.as_view(
            queryset = Item.objects.all(),
            context_object_name = 'item_list',
            template_name = 'AlbumItemList.html'
        ),
        name = 'AlbumItemList'
    ),
         
    url(r'^items/(?P<pk>\d+)/$', 
        DetailView.as_view(
            queryset = Item.objects.all(),
            context_object_name = 'item',
            template_name = 'AlbumItemDetail.html'
        ),
        name = 'AlbumItemDetail'
    ),      
                          
    url(r'^photos/(?P<pk>\d+)/$',
        DetailView.as_view(
            queryset = Photo.objects.all(),
            context_object_name = 'photo',
            template_name = 'AlbumPhotoDetail.html'
        ),
        name = 'AlbumPhotoDetail'
    ),
)

python/99-project/django-web/ExpPH/cms/urls.py
# -*- coding: utf-8 -*-

from cms.models import Story
from django.conf.urls import url, patterns


info_dict = {'queryset': Story.objects.all(), 
             'template_object_name': 'story'}

urlpatterns = patterns(
                       '',
#     'django.views.generic.list_detail',
#     url(r'^(?P<slug>[-\w]+)/$', 'object_detail', info_dict, name='cms-story'),
#     url(r'^$', 'object_list', info_dict, name='cms-home')
)

# urlpatterns += patterns(
#     'cms.views',
#     url(r'^category/(?P<slug>[-\w]+)/$', 'category', name='cms-category'),
#     url(r'^search/$', 'search', name='cms-search'),
# )

python/99-project/django-web/ExpPH/album/models.py
# -*- coding: utf8 -*-

from django.db import models
from django.contrib import admin
from album.fields import ThumbnailImageField as TIF

''' 定义相册模型 '''
class Item(models.Model):
    name = models.CharField(max_length = 20)
    description = models.TextField()
    
    class Meta:
        ordering = ['name']
        
    # 当需要使用这个字段时，返回它的unicode字符串
    def __unicode__(self):
        return self.name
    
    # 避免URL硬编码，供模板使用，格式为{% xxx.get_absolute_url %}
    # 当在模板调用这个模型的get_absolute_url方法时，就可以得到一个URL
    # 返回值是一个三元组（在urls.py定义的URL名称，一列位置参数，一个命名参数字典）
    @models.permalink
    def get_absolute_url(self):
        return ('AlbumItemDetail', None, {'pk':self.id})
# End Class Item

    
''' 定义照片模型 '''
class Photo(models.Model):
    item = models.ForeignKey(Item)
    title = models.CharField(max_length = 100)
    # upload_to 用于设置上传图片的位置
    # 以'/'开头说明是绝对位置，以'/'开头说明是相对位置
    # 相对位置会自动把上传路径添加 MEDIA_ROOT，即 MEDIA_ROOT/photos
    # 而页面访问路径则自动添加MEDIA_URL，即MEDIA_URL/photos
    image = TIF.ThumbnailImageField(upload_to = 'photos') 
    caption = models.CharField(max_length = 250, blank = True)
    
    class Meta:
        ordering = ['title']
        
    def __unicode__(self):
        return self.title
    
    @models.permalink
    def get_absolute_url(self):
        return ('AlbumPhotoDetail', None, {'pk':self.id})
# End Class Photo

    
''' 定义内联对象 '''
class PhotoInline(admin.StackedInline):
    model = Photo    
# End Class PhotoInline
    
    
''' 定义子对象的引用 '''
class ItemAdmin(admin.ModelAdmin):
    inlines = [PhotoInline] # 将有外键的子类包含进视图
# End Class ItemAdmin
    

python/99-project/django-web/ExpPH/album/views.py
# -*- coding: utf-8 -*-

python/99-project/django-web/ExpPH/album/templates/AlbumBase.html
<!DOCTYPE html>
<html>
	<head>
		<meta charset="UTF-8">
		<title>{% block title %}{% endblock %}</title>
		<style type="text/css">
		    body { margin: 30px; font-family: sans-serif; background: #fff; }
		    h1 { background: #ccf; padding: 20px; }
		    h2 { background: #ddf; padding: 10px 20px; }
		    h3 { background: #eef: padding: 5px 20px; }
		    table { width: 100%; }
		    table th { text-align: left; }
		</style>
	</head>
	<body>
	   <h1>Album</h1>
	   {% block content %}{% endblock %}
	</body>
</html>

python/99-project/django-web/ExpPH/album/templates/AlbumIndex.html
{% extends "AlbumBase.html" %}

{% block title %}Exp's Album Index{% endblock %}

{% block content %}

	<h2>Welcome to the Album!</h2>
	<p>Here you find picture of various items.Below are some highlighted items; 
	use the link at the bottom to see the full listing.</p>
	
	<h3>Showcase</h3>
	<table>
	    <tr>
	        {% for item in item_list|slice:":3" %}
	            <td>
	                <a href="{{ item.get_absolute_url }}">
	                    <b>{{ item.name }}</b>
	                    <br />
	                    {% if item.photo_set.count %}
	                        <img src="{{ item.photo_set.all.0.image.thumb_url }}" />
	                    {% else %}
	                        <span>No photos (yet)</span>
	                    {% endif %}    
	                </a>
	            </td>
	        {% endfor %}
	    </tr>
	</table>
	
	<p>
	    <a href="{% url 'AlbumItemList' %}">View the full list</a>
	</p>

{% endblock %}

python/99-project/django-web/ExpPH/album/templates/AlbumItemDetail.html
{% extends "AlbumBase.html" %}

{% block title %}
    {{ item.name }}
{% endblock %}

{% block content %}

	<p>
	    <a href="{% url 'AlbumItemList' %}">Back to Album Items' Listing</a>
	</p>
	
	<h2>{{ item.name }}</h2>
	<p>{{ item.description }}</p>
	<h3>Photos</h3>
	<table>
	   <tr>
	       <th>Title</th>
	       <th>Thumbnail</th>
	       <th>Caption</th>
	   </tr>
	   {% for photo in item.photo_set.all %}
	       <tr>
	           <td><i>{{ photo.title }}</i></td>
	           <td>
	               <a href="{{ photo.get_absolute_url }}">
	                   <img src="{{ photo.image.thumb_url }}" />
	               </a>
	           </td>
	           <td>{{ photo.caption }}</td>
	       </tr>
	   {% endfor %}
	</table>

{% endblock %}

python/99-project/django-web/ExpPH/album/templates/AlbumItemList.html
{% extends "AlbumBase.html" %}

{% block title %}Exp's Album Item List{% endblock %}

{% block content %}

	<p>
	    <a href="{% url 'AlbumIndex' %}">Back to Album Index Page</a>
	</p>
	
	<h2>Items</h2>
	{% if item_list %}
		<table>
		   <tr>
		       <th>Name</th>
		       <th>Sample Thumb</th>
		       <th>Description</th>
		   </tr>
		   {% for item in item_list %}
		       <tr>
		           <td><i>{{ item.name }}</i></td>
		           <td>
		               {% if item.photo_set.count %}
		                   <a href="{{ item.get_absolute_url }}">
		                       <img src="{{ item.photo_set.all.0.image.thumb_url }}" />
		                   </a>
		               {% else %}
		                   (No photos currently uploaded)
		               {% endif %}
		           </td>
		           <td>{{ item.description }}</td>
		       </tr>
		   {% endfor %}
		</table>
    {% else %}
        <p>There are currently no items to display.</p>
    {% endif %}

{% endblock %}

python/99-project/django-web/ExpPH/album/templates/AlbumPhotoDetail.html
{% extends "AlbumBase.html" %}

{% block title %}
    {{ photo.item.name }} - {{ photo.title }}
{% endblock %}

{% block content %}
    <a href="{{ photo.item.get_absolute_url }}">Back to {{ photo.item.name }} detail page</a>
	
	<h2>{{ photo.item.name }} - {{ photo.title }}</h2>
	<img src="{{ photo.image.url }}" />
	{% if photo.caption %}
	   <p>{{ photo.caption }}</p>
	{% endif %}
{% endblock %}